DROP DATABASE IF EXISTS MYDB0902;
CREATE DATABASE MYDB0902;
USE MYDB0902;
CREATE TABLE EXAM(
    ENO INT AUTO_INCREMENT PRIMARY KEY,
    ENAME VARCHAR(255)
);
INSERT INTO EXAM(ENAME)VALUES('유재석');
INSERT INTO EXAM(ENAME)VALUES('강호동');
INSERT INTO EXAM(ENAME)VALUES('신동엽');