plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'springweb'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {	// start.spring.io  의존성 추가
	// 1. springboot
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	// 2. mysql jdbc
	runtimeOnly 'com.mysql:mysql-connector-j'
	// 3. 롬복
	compileOnly 'org.projectlombok:lombok'
 	annotationProcessor 'org.projectlombok:lombok'
}

tasks.named('test') {
	useJUnitPlatform()
}
