DROP DATABASE IF EXISTS PT2;
CREATE DATABASE PT2;
USE PT2;
CREATE TABLE TEST(
    TNO INT AUTO_INCREMENT PRIMARY KEY,
    WRITER VARCHAR(255),
    CONTENT VARCHAR(255)
);
INSERT INTO TEST(WRITER, CONTENT)VALUES('유재석', '하이');
INSERT INTO TEST(WRITER, CONTENT)VALUES('강호동', '하이2');
INSERT INTO TEST(WRITER, CONTENT)VALUES('신동엽', '하이3');